// Copyright 2026. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"ble-session-appliance-pp-cli/internal/cliutil"
	"ble-session-appliance-pp-cli/internal/device"
	"github.com/spf13/cobra"
)

type rootFlags struct {
	asJSON    bool
	live      bool
	address   string
	timeout   time.Duration
	dryRun    bool
	storePath string
}

// deviceTransport resolves the transport at run time (after flags parse):
// LiveTransport under --live, the replay transport otherwise. Selection cannot
// happen at command-construction time because persistent flags are unparsed then.
func deviceTransport(flags *rootFlags) device.Transport {
	if flags.live {
		return device.NewLiveTransport(flags.address, flags.timeout)
	}
	return device.NewReplayTransport()
}

// novelCommands is an optional hook for hand-authored commands. It is nil by
// default (no extra commands). To extend this CLI WITHOUT editing generated
// files, add a file in package cli — it is preserved across regeneration — that
// sets this var from an init function:
//
//	func init() {
//		novelCommands = func(root *cobra.Command, flags *rootFlags) {
//			root.AddCommand(newMyCmd(flags))
//		}
//	}
var novelCommands func(root *cobra.Command, flags *rootFlags)

func RootCmd() *cobra.Command {
	var flags rootFlags
	return newRootCmd(&flags)
}

func Execute() error {
	return RootCmd().Execute()
}

func ExitCode(err error) int {
	if err == nil {
		return 0
	}
	return 1
}

func newRootCmd(flags *rootFlags) *cobra.Command {
	rootCmd := &cobra.Command{
		Use:          "ble-session-appliance-pp-cli",
		Short:        "Control BLE Session Appliance over BLE",
		Long:         "Control BLE Session Appliance over BLE using a generated device-native CLI surface.",
		Version:      version,
		SilenceUsage: true,
	}
	rootCmd.SetVersionTemplate("ble-session-appliance-pp-cli {{ .Version }}\n")
	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "Output as JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "agent", false, "Output agent-friendly JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.live, "live", false, "Contact the physical device over BLE (needs a binary built with -tags ble_live)")
	rootCmd.PersistentFlags().StringVar(&flags.address, "address", "", "BLE device address (default: auto-discover by service UUID)")
	rootCmd.PersistentFlags().DurationVar(&flags.timeout, "timeout", 20*time.Second, "Per-operation BLE timeout")
	rootCmd.PersistentFlags().BoolVar(&flags.dryRun, "dry-run", false, "Preview device writes without dispatching them")
	rootCmd.PersistentFlags().StringVar(&flags.storePath, "store", "", "Telemetry store path (default: user cache)")
	rootCmd.AddCommand(newVersionCmd())
	rootCmd.AddCommand(newCapabilitiesCmd(flags))
	rootCmd.AddCommand(newStatusCmd(flags))
	rootCmd.AddCommand(newDoctorCmd(flags))
	rootCmd.AddCommand(newScanCmd(flags))
	rootCmd.AddCommand(newSessionCmd(flags, device.NewReplaySession()))
	rootCmd.AddCommand(newTelemetryCmd(flags, device.NewReplayTransport()))
	rootCmd.AddCommand(newDeviceCommandCmd(flags, device.CommandDefinition{Name: "start", CharacteristicUUID: "fd01", Safety: "physical-effect", ValidationStatus: "replay-validated", PayloadHex: "a001", Parameters: []string{}}))
	if novelCommands != nil {
		novelCommands(rootCmd, flags)
	}
	return rootCmd
}

func writeJSON(cmd *cobra.Command, value any) error {
	enc := json.NewEncoder(cmd.OutOrStdout())
	enc.SetIndent("", "  ")
	return enc.Encode(value)
}

func newCapabilitiesCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:         "capabilities",
		Short:       "Show generated BLE capability and safety metadata",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			summary := device.Capabilities()
			if flags.asJSON {
				return writeJSON(cmd, summary)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "%s capabilities\n", summary.Device)
			fmt.Fprintf(cmd.OutOrStdout(), "protocol: %s\n", summary.Protocol)
			fmt.Fprintf(cmd.OutOrStdout(), "session: %s\n", summary.SessionMode)
			for _, field := range summary.Telemetry {
				fmt.Fprintf(cmd.OutOrStdout(), "telemetry: %s via %s store=%v\n", field.Name, field.SourceCharacteristicUUID, field.Store)
			}
			for _, command := range summary.Commands {
				if command.Callable {
					fmt.Fprintf(cmd.OutOrStdout(), "callable command: %s safety=%s characteristic=%s\n", command.Name, command.Safety, command.CharacteristicUUID)
					continue
				}
				fmt.Fprintf(cmd.OutOrStdout(), "withheld command: %s safety=%s characteristic=%s reason=%s\n", command.Name, command.Safety, command.CharacteristicUUID, command.WithheldReason)
			}
			return nil
		},
	}
}

func newStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:         "status",
		Short:       "Read device status (replay-backed by default; live with --live)",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			snapshot, err := deviceTransport(flags).Status(cmd.Context())
			if err != nil {
				return err
			}
			if flags.asJSON {
				return writeJSON(cmd, snapshot)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "%s status\n", snapshot.Device)
			fmt.Fprintf(cmd.OutOrStdout(), "transport: %s\n", snapshot.Transport)
			fmt.Fprintf(cmd.OutOrStdout(), "session: %s\n", snapshot.SessionMode)
			for _, field := range device.StatusFields {
				value := snapshot.Telemetry[field.Name]
				fmt.Fprintf(cmd.OutOrStdout(), "%s: %v\n", field.Name, value)
			}
			return nil
		},
	}
}

func newScanCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "scan",
		Short: "Discover nearby devices by their BLE service (requires --live)",
		Long:  "Scan for devices that expose this device's BLE service UUID(s). Requires --live and a binary built with -tags ble_live.",
		// Inherently live (no replay equivalent) and non-functional through the
		// MCP server, which execs the default, replay-only build. Hidden from MCP.
		Annotations: map[string]string{"mcp:hidden": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !flags.live {
				if flags.asJSON {
					return writeJSON(cmd, map[string]any{"live": false, "message": "pass --live to scan"})
				}
				fmt.Fprintln(cmd.OutOrStdout(), "not contacting any device; pass --live to scan")
				return nil
			}
			adverts, err := device.NewLiveTransport(flags.address, flags.timeout).Scan(cmd.Context())
			if err != nil {
				return err
			}
			if flags.asJSON {
				return writeJSON(cmd, map[string]any{"count": len(adverts), "devices": adverts})
			}
			if len(adverts) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "no devices found (is the device on and any official app closed?)")
				return nil
			}
			for _, advert := range adverts {
				name := advert.Name
				if name == "" {
					name = "(unnamed)"
				}
				fmt.Fprintf(cmd.OutOrStdout(), "%s  %-16s  rssi %d\n", advert.Address, name, advert.RSSI)
			}
			return nil
		},
	}
}

func newDoctorCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:         "doctor",
		Short:       "Check BLE readiness, build, and (with --live) device reachability",
		Long:        "Report whether live BLE is compiled in, the active verify/dogfood state, the device's service UUIDs, and — with --live — whether the device is reachable. Safe to run anywhere; never actuates the device.",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			info := map[string]any{
				"live_compiled": device.LiveAvailable(),
				"verify_env":    cliutil.IsVerifyEnv(),
				"dogfood_env":   cliutil.IsDogfoodEnv(),
				"service_uuids": device.ServiceUUIDs,
				"address":       flags.address,
				"transport": map[string]any{
					"write_mode":         "acknowledged",
					"command_spacing_ms": 690,
					"poll_cadence_ms":    500,
					"teardown":           "keep-running",
					"single_client":      true,
				},
			}
			// Operating quirks synthesized from the device's protocol sources: these
			// cannot be auto-handled, so doctor surfaces them for the operator/agent.
			info["quirks"] = []map[string]string{
				{"category": "concurrency", "summary": "The vendor app holds the single BLE slot; disconnect it before laptop control.", "handling": "doctor surfaces this; suggest closing the app on a connect failure."},
			}
			// Proven operating workflows: the cited reference spine the implemented
			// control flow is expected to follow. Surfaced (not codegen) so an
			// operator/agent can confirm the codec and held-connection choreography
			// match the sequence rather than rediscovering it on hardware.
			info["workflows"] = []map[string]any{
				{
					"name":  "start-appliance",
					"goal":  "Bring the appliance up and hold it running over a sustained connection.",
					"notes": "A one-shot write does not sustain the appliance; the session holds the connection open.",
					"steps": []string{
						"Subscribe to the status characteristic (fd02).",
						"Run the connect ceremony (enable-notify), then let it settle.",
						"Send start (a001) on the control characteristic (fd01).",
						"Poll status at the transport poll cadence and hold the connection.",
					},
				},
			}
			// Probe hardware only when explicitly live, the BLE backend is
			// compiled in, and not under verify.
			probe := flags.live && device.LiveAvailable() && !cliutil.IsVerifyEnv()
			info["hardware_probe"] = probe
			if probe {
				adverts, err := device.NewLiveTransport(flags.address, flags.timeout).Scan(cmd.Context())
				if err != nil {
					info["scan_error"] = err.Error()
					info["reachable"] = false
				} else {
					info["found"] = len(adverts)
					info["reachable"] = len(adverts) > 0
					info["devices"] = adverts
				}
			}
			if flags.asJSON {
				return writeJSON(cmd, info)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "live BLE compiled: %v\n", info["live_compiled"])
			fmt.Fprintf(cmd.OutOrStdout(), "verify env: %v\n", info["verify_env"])
			fmt.Fprintf(cmd.OutOrStdout(), "dogfood env: %v\n", info["dogfood_env"])
			fmt.Fprintf(cmd.OutOrStdout(), "service uuids: %v\n", info["service_uuids"])
			fmt.Fprintf(cmd.OutOrStdout(), "command spacing: %dms\n", 690)
			fmt.Fprintln(cmd.OutOrStdout(), "operating notes:")
			for _, q := range info["quirks"].([]map[string]string) {
				fmt.Fprintf(cmd.OutOrStdout(), "  - [%s] %s\n", q["category"], q["summary"])
			}
			fmt.Fprintln(cmd.OutOrStdout(), "proven workflows:")
			for _, w := range info["workflows"].([]map[string]any) {
				steps := len(w["steps"].([]string))
				if goal, _ := w["goal"].(string); goal != "" {
					fmt.Fprintf(cmd.OutOrStdout(), "  - %s: %s (%d steps)\n", w["name"], goal, steps)
				} else {
					fmt.Fprintf(cmd.OutOrStdout(), "  - %s (%d steps)\n", w["name"], steps)
				}
			}
			if !probe {
				if !device.LiveAvailable() {
					fmt.Fprintln(cmd.OutOrStdout(), "hardware probe: skipped (rebuild with -tags ble_live to enable live BLE)")
				} else {
					fmt.Fprintln(cmd.OutOrStdout(), "hardware probe: skipped (pass --live to probe the device)")
				}
				return nil
			}
			if errStr, ok := info["scan_error"].(string); ok {
				fmt.Fprintf(cmd.OutOrStdout(), "reachable: false (%s)\n", errStr)
				return nil
			}
			fmt.Fprintf(cmd.OutOrStdout(), "reachable: %v (found %v device(s))\n", info["reachable"], info["found"])
			return nil
		},
	}
}

func newDeviceCommandCmd(flags *rootFlags, definition device.CommandDefinition) *cobra.Command {
	var confirmPhysicalEffect bool
	use := definition.Name
	for _, param := range definition.Parameters {
		use += " <" + param + ">"
	}
	command := &cobra.Command{
		Use:   use,
		Short: fmt.Sprintf("Run %s (replay-backed by default; sends to the device with --live)", definition.Name),
		Args:  cobra.ExactArgs(len(definition.Parameters)),
		RunE: func(cmd *cobra.Command, args []string) error {
			if requiresPhysicalConfirmation(definition) && !flags.dryRun && !confirmPhysicalEffect && !cliutil.IsVerifyEnv() {
				return fmt.Errorf("%s has safety class %s; pass --dry-run to preview or --confirm-physical-effect to run it", definition.Name, definition.Safety)
			}
			result, err := deviceTransport(flags).ExecuteCommand(cmd.Context(), definition, args, flags.dryRun)
			if err != nil {
				return err
			}
			if flags.asJSON {
				return writeJSON(cmd, result)
			}
			if result.DryRun {
				fmt.Fprintf(cmd.OutOrStdout(), "would write %s to %s for %s\n", result.PayloadHex, result.CharacteristicUUID, result.Command)
				return nil
			}
			fmt.Fprintf(cmd.OutOrStdout(), "%s via %s\n", result.Command, result.Transport)
			return nil
		},
	}
	if requiresPhysicalConfirmation(definition) {
		command.Flags().BoolVar(&confirmPhysicalEffect, "confirm-physical-effect", false, "Confirm a physical-effect or configuration-risk device command")
	}
	return command
}

func requiresPhysicalConfirmation(definition device.CommandDefinition) bool {
	switch definition.Safety {
	case "physical-effect", "configuration-risk":
		return true
	default:
		return false
	}
}

func newTelemetryCmd(flags *rootFlags, transport device.Transport) *cobra.Command {
	telemetryCmd := &cobra.Command{
		Use:   "telemetry",
		Short: "Capture and read replay-backed telemetry samples",
	}
	telemetryCmd.AddCommand(newTelemetryCaptureCmd(flags, transport))
	telemetryCmd.AddCommand(newTelemetryLatestCmd(flags))
	telemetryCmd.AddCommand(newTelemetrySessionsCmd(flags))
	return telemetryCmd
}

func newTelemetryCaptureCmd(flags *rootFlags, transport device.Transport) *cobra.Command {
	return &cobra.Command{
		Use:   "capture",
		Short: "Capture a replay-backed telemetry sample into the local store",
		RunE: func(cmd *cobra.Command, args []string) error {
			snapshot, err := transport.Status(cmd.Context())
			if err != nil {
				return err
			}
			store, err := openTelemetryStore(flags)
			if err != nil {
				return err
			}
			samples, err := store.CaptureStatus(snapshot)
			if err != nil {
				return err
			}
			if flags.asJSON {
				return writeJSON(cmd, samples)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "captured %d telemetry sample(s)\n", len(samples))
			fmt.Fprintf(cmd.OutOrStdout(), "store: %s\n", store.Path())
			return nil
		},
	}
}

func newTelemetryLatestCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:         "latest",
		Short:       "Read the latest locally stored telemetry samples",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			store, err := openTelemetryStore(flags)
			if err != nil {
				return err
			}
			samples, err := store.Latest()
			if err != nil {
				return err
			}
			if flags.asJSON {
				return writeJSON(cmd, samples)
			}
			if len(samples) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "no stored telemetry samples")
				fmt.Fprintf(cmd.OutOrStdout(), "store: %s\n", store.Path())
				return nil
			}
			for _, sample := range samples {
				fmt.Fprintf(cmd.OutOrStdout(), "%s: %v\n", sample.Field, sample.Value)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "store: %s\n", store.Path())
			return nil
		},
	}
}

func newTelemetrySessionsCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:         "sessions",
		Short:       "Read locally stored BLE session summaries",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			store, err := openTelemetryStore(flags)
			if err != nil {
				return err
			}
			summaries, err := store.SessionSummaries()
			if err != nil {
				return err
			}
			if flags.asJSON {
				return writeJSON(cmd, summaries)
			}
			if len(summaries) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "no stored session summaries")
				fmt.Fprintf(cmd.OutOrStdout(), "store: %s\n", store.SessionPath())
				return nil
			}
			for _, summary := range summaries {
				fmt.Fprintf(cmd.OutOrStdout(), "%s: %s via %s\n", summary.ObservedAt, summary.State, summary.Transport)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "store: %s\n", store.SessionPath())
			return nil
		},
	}
}

func openTelemetryStore(flags *rootFlags) (*device.TelemetryStore, error) {
	storePath := flags.storePath
	if storePath == "" {
		var err error
		storePath, err = device.DefaultTelemetryStorePath("ble-session-appliance-pp-cli")
		if err != nil {
			return nil, err
		}
	}
	return device.OpenTelemetryStore(storePath)
}

func newSessionCmd(flags *rootFlags, session device.Session) *cobra.Command {
	sessionCmd := &cobra.Command{
		Use:   "session",
		Short: "Manage the replay-backed local BLE session runtime",
	}
	sessionCmd.AddCommand(newSessionStatusCmd(flags, session))
	sessionCmd.AddCommand(newSessionStartCmd(flags, session))
	sessionCmd.AddCommand(newSessionStopCmd(flags, session))
	return sessionCmd
}

func newSessionStatusCmd(flags *rootFlags, session device.Session) *cobra.Command {
	return &cobra.Command{
		Use:         "status",
		Short:       "Show generated BLE session requirements",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			status, err := session.Status(cmd.Context())
			if err != nil {
				return err
			}
			return writeSessionStatus(cmd, flags, status)
		},
	}
}

func newSessionStartCmd(flags *rootFlags, session device.Session) *cobra.Command {
	return &cobra.Command{
		Use:   "start",
		Short: "Start the replay-backed local BLE session runtime",
		RunE: func(cmd *cobra.Command, args []string) error {
			status, err := session.Start(cmd.Context())
			if err != nil {
				return err
			}
			if err := captureSessionSummary(flags, status); err != nil {
				return err
			}
			return writeSessionStatus(cmd, flags, status)
		},
	}
}

func newSessionStopCmd(flags *rootFlags, session device.Session) *cobra.Command {
	return &cobra.Command{
		Use:   "stop",
		Short: "Stop the replay-backed local BLE session runtime",
		RunE: func(cmd *cobra.Command, args []string) error {
			status, err := session.Stop(cmd.Context())
			if err != nil {
				return err
			}
			if err := captureSessionSummary(flags, status); err != nil {
				return err
			}
			return writeSessionStatus(cmd, flags, status)
		},
	}
}

func captureSessionSummary(flags *rootFlags, status device.SessionStatus) error {
	store, err := openTelemetryStore(flags)
	if err != nil {
		return err
	}
	_, err = store.CaptureSession(status)
	return err
}

func writeSessionStatus(cmd *cobra.Command, flags *rootFlags, status device.SessionStatus) error {
	if flags.asJSON {
		return writeJSON(cmd, status)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "%s session\n", status.Device)
	fmt.Fprintf(cmd.OutOrStdout(), "state: %s\n", status.State)
	fmt.Fprintf(cmd.OutOrStdout(), "mode: %s\n", status.Mode)
	fmt.Fprintf(cmd.OutOrStdout(), "transport: %s\n", status.Transport)
	fmt.Fprintf(cmd.OutOrStdout(), "endpoint: %s %s\n", status.Endpoint.Kind, status.Endpoint.Path)
	fmt.Fprintf(cmd.OutOrStdout(), "runtime: %s\n", status.RuntimeDir)
	fmt.Fprintf(cmd.OutOrStdout(), "token: %v\n", status.TokenPresent)
	fmt.Fprintf(cmd.OutOrStdout(), "one-shot fallback: %v\n", status.OneShotFallback)
	fmt.Fprintf(cmd.OutOrStdout(), "reconnect: %v\n", status.Reconnect)
	fmt.Fprintf(cmd.OutOrStdout(), "notification stream: %v\n", status.NotificationStream)
	for _, reason := range status.Reasons {
		fmt.Fprintf(cmd.OutOrStdout(), "reason: %s\n", reason)
	}
	if status.Detail != "" {
		fmt.Fprintf(cmd.OutOrStdout(), "detail: %s\n", status.Detail)
	}
	return nil
}

func ExecuteWithContext(ctx context.Context) error {
	cmd := RootCmd()
	cmd.SetContext(ctx)
	return cmd.Execute()
}
