// Copyright 2026. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package device

const (
	Name                      = "ble-session-appliance"
	DisplayName               = "BLE Session Appliance"
	Protocol                  = "ble"
	SessionMode               = "optional"
	SessionOneShotFallback    = true
	SessionReconnect          = true
	SessionNotificationStream = true
)

var SessionReasons = []string{
	"low_latency_controls",
	"notification_stream",
	"telemetry_sampling",
	"reconnect",
}

// ServiceUUIDs are the device's BLE GATT service UUIDs, used to discover and
// connect to the device (matching by service rather than advertised name).
var ServiceUUIDs = []string{
	"fd00",
}

type StatusField struct {
	Name                     string `json:"name"`
	SourceCharacteristicUUID string `json:"source_characteristic_uuid"`
	Unit                     string `json:"unit,omitempty"`
	SampleCadence            string `json:"sample_cadence,omitempty"`
	Store                    bool   `json:"store,omitempty"`
}

var StatusFields = []StatusField{
	{Name: "run_state", SourceCharacteristicUUID: "fd02", Unit: "", SampleCadence: "notification", Store: true},
}

type CommandDefinition struct {
	Name               string   `json:"name"`
	CharacteristicUUID string   `json:"characteristic_uuid"`
	Safety             string   `json:"safety"`
	ValidationStatus   string   `json:"validation_status,omitempty"`
	PayloadHex         string   `json:"payload_hex"`
	EvidenceRefs       []string `json:"evidence_refs,omitempty"`
	Parameters         []string `json:"parameters,omitempty"`
}

var CommandDefinitions = []CommandDefinition{
	{Name: "start", CharacteristicUUID: "fd01", Safety: "physical-effect", ValidationStatus: "replay-validated", PayloadHex: "a001", EvidenceRefs: []string{"write-start", "notify-running"}, Parameters: []string{}},
}

type CommandCapability struct {
	Name               string   `json:"name"`
	CharacteristicUUID string   `json:"characteristic_uuid"`
	Safety             string   `json:"safety"`
	ValidationStatus   string   `json:"validation_status,omitempty"`
	EvidenceRefs       []string `json:"evidence_refs,omitempty"`
	Callable           bool     `json:"callable"`
	WithheldReason     string   `json:"withheld_reason,omitempty"`
}

var CommandCapabilities = []CommandCapability{
	{Name: "start", CharacteristicUUID: "fd01", Safety: "physical-effect", ValidationStatus: "replay-validated", EvidenceRefs: []string{"write-start", "notify-running"}, Callable: true, WithheldReason: ""},
}

type CapabilitySummary struct {
	Device      string              `json:"device"`
	Protocol    string              `json:"protocol"`
	SessionMode string              `json:"session_mode"`
	Telemetry   []StatusField       `json:"telemetry"`
	Commands    []CommandCapability `json:"commands"`
}

func Capabilities() CapabilitySummary {
	return CapabilitySummary{
		Device:      DisplayName,
		Protocol:    Protocol,
		SessionMode: SessionMode,
		Telemetry:   append([]StatusField(nil), StatusFields...),
		Commands:    append([]CommandCapability(nil), CommandCapabilities...),
	}
}
